### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by JannikSchneider12** [wh-xu/Hyper-Spec#1]
Hey,

I am using wsl and tried to install via cloning the repo, create an environment with "mamba env create --name hyperspec -f requirements.yaml' and not want to run the tool. However when I am running "python src/main.py -h", I am getting this error:

Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    import hd_preprocess, hd_cluster
  File "/home/jannik/hyperspec/Hyper-Spec/src/hd_cluster.py", line 13, in <module>
    import cuml, rmm
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/cuml/__init__.py", line 17, in <module>
    from cuml.common.base import Base
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/cuml/common/__init__.py", line 17, in <module>
    from cuml.common.array import CumlArray
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/cuml/common/array.py", line 25, in <module>
    from cudf import DataFrame
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
    from rmm._cuda.gpu import (
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/home/jannik/mambaforge/envs/hyperspec/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))

This is my virtual environment
------------------------------------------------------------------------------------------------------------------------------------

(hyperspec) jannik@DELLXPS:~/hyperspec/Hyper-Spec$ conda list
# packages in environment at /home/jannik/mambaforge/envs/hyperspec:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abseil-cpp                20211102.0           hd4dd3e8_0
apache-arrow-proc         4.0.0                      cuda    conda-forge
arrow-cpp                 6.0.1           py38h97bb493_20_cuda    conda-forge
arrow-cpp-proc            4.0.0                      cuda    conda-forge
aws-c-cal                 0.5.11               h95a6274_0    conda-forge
aws-c-common              0.6.2                h27cfd23_0
aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
aws-c-io                  0.10.5               hfb6a706_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hecaee15_4    conda-forge
blas                      1.0                         mkl
bokeh                     2.4.3            py38h06a4308_0
bottleneck                1.3.4            py38hce1f21e_0
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.1               h5eee18b_0
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0
click                     8.0.4            py38h06a4308_0
cloudpickle               2.2.1            py38h06a4308_0
configargparse            1.4                pyhd3eb1b0_0
cuda-python               11.8.3           py38h1986e8c_0    conda-forge
cuda-version              11.2                 hb11dac2_2    conda-forge
cudatoolkit               11.2.2              hc23eb0c_12    conda-forge
cudf                      22.04.00        cuda_11_py38_g8bf0520170_0    rapidsai
cuml                      22.04.00        cuda11_py38_g95abbc746_0    rapidsai
cupy                      10.6.0           py38h405e1b6_0    conda-forge
cython                    0.29.28          py38h295c915_0
cytoolz                   0.12.2           py38h5eee18b_0
daal4py                   2021.5.0         py38h78b71dc_0
dal                       2021.5.1           h06a4308_803
dask                      2022.3.0           pyhd8ed1ab_1    conda-forge
dask-core                 2022.3.0           pyhd8ed1ab_0    conda-forge
dask-cuda                 22.4.0             pyhd8ed1ab_1    conda-forge
dask-cudf                 22.04.00        cuda_11_py38_g8bf0520170_0    rapidsai
distributed               2022.3.0           pyhd8ed1ab_0    conda-forge
dlpack                    0.5                  h9c3ff4c_0    conda-forge
faiss-proc                1.0.0                      cuda    conda-forge
fastavro                  1.7.0            py38h5eee18b_0
fastcluster               1.2.6            py38h1128e8f_0
fastrlock                 0.8.2            py38h17151c0_1    conda-forge
freetype                  2.12.1               h4a9f257_0
fsspec                    2023.10.0        py38h06a4308_0
gflags                    2.2.2                he6710b0_0
giflib                    5.2.1                h5eee18b_3
glog                      0.6.0                h6f12383_0    conda-forge
grpc-cpp                  1.45.2               he70e3f0_3    conda-forge
heapdict                  1.0.1              pyhd3eb1b0_0
icu                       73.1                 h6a678d5_0
intel-openmp              2023.1.0         hdb19cb5_46306
jinja2                    3.1.2            py38h06a4308_0
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9e                   h5eee18b_1
krb5                      1.20.1               h568e23c_1
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libcblas                  3.9.0           5_h92ddd45_netlib    conda-forge
libcudf                   22.04.00        cuda11_g8bf0520170_0    rapidsai
libcuml                   22.04.00        cuda11_g95abbc746_0    rapidsai
libcumlprims              22.04.00        cuda11_g286c803_0    nvidia
libcurl                   8.2.1                h91b91d3_0
libcusolver               11.5.4.101                    0    nvidia
libdeflate                1.17                 h5eee18b_1
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libevent                  2.1.10               h9b69904_4    conda-forge
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libgomp                   13.2.0               h807b86a_3    conda-forge
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
libllvm11                 11.1.0               h9e868ea_6
libmagic                  5.36                 h27cfd23_2
libnghttp2                1.52.0               ha637b67_1
libpng                    1.6.39               h5eee18b_0
libprotobuf               3.20.3               he621ea3_0
libraft-distance          22.04.00        cuda11_ge987ec8_0    rapidsai
libraft-headers           22.04.00        cuda11_ge987ec8_0    rapidsai
libraft-nn                22.04.00        cuda11_ge987ec8_0    rapidsai
librmm                    22.04.01             h65003ff_1    conda-forge
libssh2                   1.10.0               h37d81fd_2
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libthrift                 0.16.0               h491838f_2    conda-forge
libtiff                   4.5.1                h6a678d5_0
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libwebp                   1.3.2                h11a3e52_0
libwebp-base              1.3.2                h5eee18b_0
libxml2                   2.10.4               hf1b16e4_1
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.38.0           py38h4ff587b_0
locket                    1.0.0            py38h06a4308_0
lz4                       4.3.2            py38h5eee18b_0
lz4-c                     1.9.4                h6a678d5_0
markupsafe                2.1.1            py38h7f8727e_0
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0            py38h5eee18b_1
mkl_fft                   1.3.8            py38h5eee18b_0
mkl_random                1.2.4            py38hdb19cb5_0
mpi                       1.0                       mpich
mpich                     3.3.2                external_0
msgpack-python            1.0.3            py38hd09550d_0
nccl                      2.19.4.1             h0800d71_0    conda-forge
ncurses                   6.4                  h6a678d5_0
numba                     0.55.1           py38h51133e4_0
numexpr                   2.8.4            py38hc78ab66_1
numpy                     1.21.5           py38hf6e8229_4
numpy-base                1.21.5           py38h060ed82_4
nvtx                      0.2.8            py38h01eb140_1    conda-forge
openjpeg                  2.4.0                h3ad879b_0
openssl                   1.1.1w               h7f8727e_0
orc                       1.7.5                h6c59b99_0    conda-forge
packaging                 23.1             py38h06a4308_0
pandas                    1.3.5            py38h8c16a72_0
parquet-cpp               1.5.1                h34088ae_4
partd                     1.4.1            py38h06a4308_0
pillow                    10.0.1           py38ha6cbd5a_0
pip                       21.2.4           py38h06a4308_0
protobuf                  3.20.3           py38h6a678d5_0
psutil                    5.9.0            py38h5eee18b_0
ptxcompiler               0.8.1            py38h1986e8c_2    conda-forge
pyarrow                   6.0.1           py38h17143e8_20_cuda    conda-forge
pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
pyraft                    22.04.00        cuda11_py38_ge987ec8_0    rapidsai
python                    3.8.18               h7a1cb2a_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-lmdb               1.4.1            py38h6a678d5_0
python-magic              0.4.27           py38h578d9bd_4    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2023.3.post1     py38h06a4308_0
pyyaml                    6.0.1            py38h5eee18b_0
re2                       2022.04.01           h295c915_0
readline                  8.2                  h5eee18b_0
rmm                       22.04.01        cuda11_py38_g9e30c3a_0    rapidsai
s2n                       1.0.10               h9b69904_0    conda-forge
s3cmd                     2.0.2                      py_0    conda-forge
scikit-learn              1.0.2            py38h51133e4_1
scikit-learn-intelex      2021.5.0         py38h06a4308_0
scipy                     1.7.3            py38h8ce737c_1    conda-forge
setuptools                68.0.0           py38h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h295c915_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
spdlog                    1.10.0               h924138e_0    conda-forge
sqlite                    3.41.2               h5eee18b_0
tbb                       2021.8.0             hdb19cb5_0
tblib                     1.7.0              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
thrust                    1.16.0               h0800d71_2    conda-forge
tk                        8.6.12               h1ccaba5_0
toolz                     0.12.0           py38h06a4308_0
tornado                   6.1              py38h27cfd23_0
tqdm                      4.64.0           py38h06a4308_0
treelite                  2.3.0            py38hdd725b4_0    conda-forge
treelite-runtime          2.3.0                    pypi_0    pypi
typing_extensions         4.7.1            py38h06a4308_0
ucx                       1.12.0+gd367332      cuda11.2_0    rapidsai
ucx-proc                  1.0.0                       gpu    conda-forge
ucx-py                    0.25.00         py38_gd367332_0    rapidsai
wheel                     0.41.2           py38h06a4308_0
xz                        5.4.5                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
zict                      3.0.0            py38h06a4308_0
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0

Could anyone help me?

Thanks for your time and help

**Comment by JannikSchneider12** [comment]
Edit:

When I am using docker, I am getting the same error:

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

(hyper-spec) root@df0eaf97b773:/Hyper-Spec# python src/main.py -h
Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    import hd_preprocess, hd_cluster
  File "/Hyper-Spec/src/hd_cluster.py", line 13, in <module>
    import cuml, rmm
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/cuml/__init__.py", line 17, in <module>
    from cuml.common.base import Base
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/cuml/common/__init__.py", line 17, in <module>
    from cuml.common.array import CumlArray
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/cuml/common/array.py", line 25, in <module>
    from cudf import DataFrame
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/envs/hyper-spec/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))

**Comment by JannikSchneider12** [comment]
Edit: this solved the problem for me:

conda install -c nvidia cuda-python=11.7.0
